### ISSUE TITLE
Provision server-settings.json through variables

### ISSUE THREAD

**Issue by deveth0** [dtandersen/docker_factorio_server#197]
Hi,
i currently try to run a number of servers parallel using this awesome docker image. One thing i'm really missing is the possibility, to preconfigure the server-settings in docker-compose.
This would allow to set the variables and then run the server.

Might this be a possibility? Cheers

**Comment by dtandersen** [comment]
It's not planned to do that. But you could fork this repo and create your own entrypoint.sh. Then have docker hub auto build it when the base image changes.

**Comment by deveth0** [comment]
OK, that was what I thought of next. Thanks for the fast feedback and your work!!!

**Comment by dtandersen** [comment]
Out of curiosity which settings would you want?

My main concern with this is we're gonna end up with every friggin server option as an ENV.

On the other hand, stateless deployments are good.

**Comment by deveth0** [comment]
I think at least username, api token, server name, server description and probably the server password would be nice.

**Comment by dtandersen** [comment]
envsubst perhaps...

https://hub.docker.com/_/nginx

```
web:
  image: nginx
  volumes:
   - ./mysite.template:/etc/nginx/conf.d/mysite.template
  ports:
   - "8080:80"
  environment:
   - NGINX_HOST=foobar.com
   - NGINX_PORT=80
  command: /bin/bash -c "envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
```
