### ISSUE TITLE
Scenarios

### ISSUE THREAD

**Issue by ArunKalahasti** [dtandersen/docker_factorio_server#32]
Would it be possible to include variables to launch the server with scenarios?

**Comment by dtandersen** [comment]
See https://github.com/dtandersen/docker_factorio_server/pull/46.

**Comment by dtandersen** [comment]
```
version: '2'
services:
  factorio:
    image: dtandersen/factorio:scenario
    ports:
      - "34197:34197"
    volumes:
      - /tmp/factorio:/factorio
    command:
      - --server-settings
      - /factorio/config/server-settings.json
      - --start-server-load-scenario
      - base/wave-defense
```
