### ISSUE TITLE
Add sample docker-compose.yml to README

### ISSUE THREAD

**Issue by ckeeney** [dtandersen/docker_factorio_server#56]
I've been running docker for a couple years, and I find using docker-compose makes it easier to maintain docker services without having to specify all the CLI args to run the docker.  I just keep all my `docker-compose.yml` files in `/opt/` and can easily start and stop any services I want, as well as see all the docker settings for each service.

I'm going to setup my `docker-compose.yml` based on this image, and am happy to open a PR adding some docs to the README about how to do this after I'm done.

**Comment by dtandersen** [comment]
There's one in the 0.15 folder. Might want to mention it in the README.

**Comment by j2ghz** [comment]
It may be better to show something like this as example:
```yml
version: "2"
services:
  factorio:
    image: dtandersen/factorio:0.15.23
    ports:
      - "34197:34197/udp"
      - "27015:27015"
    volumes:
      - "/opt/factorio:/factorio"
```
This one can be used stand-alone, [the one in 0.15 folder](https://github.com/dtandersen/docker_factorio_server/blob/master/0.15/docker-compose.yml#L4) needs the Dockerfile and entrypoint.
