### ISSUE TITLE
Kubernetes example

### ISSUE THREAD

**Issue by fire** [dtandersen/docker_factorio_server#79]
Not sure how to size the backups, but here's an example kubernetes setup.

```
---
apiVersion: v1
kind: Service
metadata:
  name: factorio
  labels:
    app: factorio
spec:
  ports:
  - port: 34197
    name: factorio
    protocol: UDP
  type: LoadBalancer
  selector:
    app: factorio
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: factorio
spec:
  serviceName: "factorio"
  replicas: 1
  selector:
    matchLabels:
      app: factorio
  template:
    metadata:
      labels:
        app: factorio
    spec:
      containers:
      - name: nginx
        image: dtandersen/factorio:0.15.37
        env:
          - name: PORT
            value: "34197"
        ports:
        - containerPort: 34197
          name: web
          protocol: UDP
        volumeMounts:
        - name: saves
          mountPath: /factorio
  volumeClaimTemplates:
  - metadata:
      name: saves
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi
```
